# 100 numpy exercises

If you are not familiar with with Numpy, check out this introduciton - https://numpy.org/doc/stable/user/absolute_beginners.html

Please do not user LLMs to solve these problems

This excercise is using questions from
free to open an issue at <https://github.com/rougier/numpy-100>.

## Basic Numpy understanding

#### 1. Import the numpy package under the name `np` (★☆☆)

In [ ]:
import numpy as np

#### 4. Crate the vector `[0, 1, ..., 99]`. Find the memory size of it (with `arr.nbytes`) - why is that the size? (★☆☆)

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

#### 11. Create a 3x3 identity matrix (★☆☆)

#### 12. Create a 3x3x3 array with random values (uniformly from 0 to 1) (★☆☆)

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

#### 89. How to get the n largest values of an array (★★★)

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [ ]:
arr = np.ones((3, 3))
'''
Wanted result:
array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])
'''

# your code here

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [ ]:
A = np.arange(15).reshape(5, 3)
B = np.arange(6).reshape(3, 2)

'''
Wanted result:
array([[ 10,  13],
       [ 28,  40],
       [ 46,  67],
       [ 64,  94],
       [ 82, 121]])
'''

# your code here

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [ ]:
A = np.ones(3)*1
B = np.ones(3)*2

'''
Wanted result:

array([-1.5, -1.5, -1.5])
'''

# your code here

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

#### 40. Create a random vector of size 10 and sort it (★★☆)

#### 72. How to swap two rows of an array? (★★★)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area in a given size `n` (★★☆)

In [ ]:
'''
for n=5, wanted result:

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]

 '''

n = 5
# your code here

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [ ]:
np.abs(v - x)

29.70486263015348

In [ ]:
v = np.random.rand(1000)
x = 0.41

# your code here

0.410148522288041

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [ ]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))

# your code here

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★☆)
create an array F such that each index i in F contains the sum of all X[j] where I[j] == i

In [ ]:
X = [1, 2, 3, 4, 5, 6]
I = [1, 3, 9, 3, 4, 1]

'''
wanted result:
    [0, 7, 0, 6, 5, 0, 0, 0, 0, 3]
'''

# hint - read about np.bincount

# your code here

## Advanced operations

#### 68. Considering a one-dimensional vector D, how to compute means (not sums) of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [ ]:
D = [13, 14, 10, 10, 12]
S = [3, 0, 2, 1, 2]

'''
wanted result:
    [14. 10. 11. 13.]
'''

# your code here

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to multiply it by an array with dimensions (5,5)? (★★★)

In [ ]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))

# hint - https://i.sstatic.net/zkMBy.png

# your code here

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (only with np ops of course) (★★★)

#### 75. How to compute sum over sliding window on an np.arr? (★★★)

In [ ]:
from numpy.lib.stride_tricks import sliding_window_view

Z = [0, 1, 2, 3, 4, 5]
window_size = 3

'''
wanted result:
    [3, 6, 9, 12]
'''

# your code here

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

In [ ]:
# hint: use np.linalg.svd

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### Given a 3D array A of shape (2, 3, 4) and a 2D array B of shape (4, 5), compute the result of multiplying the last dimension of A with the first dimension of B, across all batches. (★★★)

In [ ]:
# hint: use np.einsum

Check yourself at - https://github.com/rougier/numpy-100/blob/master/100_Numpy_exercises_with_solutions.md <br>
Do not use it before finishing the excercise!

## 🔥 Summary Exercise: City Traffic Sensor Grid Analysis (★★★★★★)

### 🧠 Background  
You're analyzing data from a **10×10 grid of traffic sensors** at a busy urban intersection. Each sensor records **hourly traffic** (number of cars) for an entire month.


### 📦 Provided Data

You are given a NumPy array `traffic` with shape `(28, 24, 10, 10)`, representing:

- 28 days  
- 24 hours per day  
- 10×10 grid of sensors  


⛔ Constraints

- Use **NumPy only** — no external libraries.  
- **No loops** — prefer **fully vectorized** solutions.  
- Prioritize **readability** and **efficiency**.



In [ ]:
import numpy as np

np.random.seed(0xCAFEBABE)
traffic = np.load('traffic.npy')

Determine the **(i, j)** location of the sensor with the **highest average hourly traffic** over the entire month.


Find the **hotspots** (high traffic ereas) in this town (hint: in different hours people tend to go to different places), define it the way you see fit

Perform a **3×3 sliding window sum** over the **daily-aggregated grid** (i.e., sum over 24 hours for each sensor per day).  
Identify the **location and day** with the highest 3×3 traffic region.

Track the **(i, j)** location of the **busiest sensor each day**.  
Count how many times the hotspot moved **more than 3 grid cells** from the previous day.

### 📊 Grid & Traffic System Performance

You are given:

1. A `traffic_light_types` array: **10×10 grid** type of traffic light system in each grid cell (each value is in {0, 1, 2, 3}).
2. A `traffic_light_weights` array: how much the traffic is important for each traffic light weights.
3. A `hourly_weights` array: how much the traffic is important for each hour of the day.
4. A `daily_weights` array: how much the traffic is important for each day of the week.


In [ ]:
# 10x10 grid of system types (0 to 3)
traffic_light_types = np.array(
      [[3, 2, 3, 3, 2, 3, 3, 3, 2, 3],
       [2, 3, 3, 2, 3, 2, 3, 3, 3, 3],
       [3, 3, 3, 3, 2, 3, 0, 2, 3, 2],
       [3, 2, 1, 2, 3, 3, 3, 3, 3, 2],
       [3, 2, 2, 3, 3, 3, 1, 3, 3, 3],
       [1, 3, 1, 3, 1, 3, 3, 3, 2, 1],
       [3, 2, 3, 3, 3, 3, 0, 2, 3, 1],
       [3, 1, 2, 0, 3, 2, 2, 3, 3, 1],
       [1, 3, 3, 2, 3, 3, 3, 3, 3, 2],
       [2, 2, 1, 3, 3, 3, 2, 2, 1, 2]]
    )

# importance of each place in town
traffic_light_weights = np.array([26.0, 4.0, 2.5, 1.0])

hourly_weights = [0.7, 1.4, 0.7, 0.8, 0.8, 0.7,
                  0.8, 0.9, 0.6, 0.7, 1.4, 0.6,
                  0.9, 1.1, 1.3, 0.7, 0.8, 0.5,
                  0.5, 1.1, 0.5, 1.1, 0.8, 0.8]

daily_weights = [1.0 ,0.6, 0.5, 1.4, 1.5, 1.9, 2.3] # weekly

### 🎯 Your Goal

Due to budget constraints, the city can **replace all traffic lights between two types** (e.g., all 3s to 1s and all 1s to 3s). You must:

1. Try all possible upgrades (`from_type ≠ to_type`) (can use loop here, even that possible without).
2. For each, calculate the **total traffic** over all 744 hours, **weighted** by traffic load (hourly × daily).
3. Find the **best upgrade** — the one that **maximizes the weighted total performance**.
4. Return:
   - The best `(from_type, to_type)` pair
   - The **new weighted score** (in "weighted traffic" units).
   - The **improvement** compared to the original system.
